import type { LoadBitmapFontOptions } from './FontLoader';

export interface FontPreset extends LoadBitmapFontOptions {
  glyphCount: number;
  charWidth: number;
  charHeight: number;
  bytesPerGlyph: number;
  computer: string;
  description: string;
  mapperId: 'ascii' | 'petscii';
}

const msb8 = [7, 6, 5, 4, 3, 2, 1, 0];
const lsb8 = [0, 1, 2, 3, 4, 5, 6, 7];

export const fontPresets: FontPreset[] = [
  {
    id: 'zx-spectrum',
    name: 'ZX Spectrum',
    url: '/fonts/zx-spectrum/zx-spectrum.bin',
    computer: 'ZX Spectrum',
    description: 'ZX Spectrum ROM font (1024B, 128 glyphs)',
    glyphCount: 128,
    charWidth: 8, charHeight: 8, bytesPerGlyph: 8,
    bitOrder: 'msb-left', offset: 0,
    xBits: msb8,
    mapperId: 'ascii',
  },
  {
    id: 'c64-chargen',
    name: 'Commodore 64',
    url: '/fonts/c64/chargen.bin',
    computer: 'Commodore 64',
    description: 'C64 CHARGEN (2 sets, 4096B)',
    glyphCount: 512,
    charWidth: 8, charHeight: 8, bytesPerGlyph: 8,
    bitOrder: 'msb-left', offset: 0,
    xBits: msb8,
    mapperId: 'petscii',
  },
  {
    id: 'c64-chargen-first',
    name: 'C64 (uppercase set)',
    url: '/fonts/c64/chargen.bin',
    computer: 'Commodore 64',
    description: 'C64 CHARGEN first 256 glyphs',
    glyphCount: 256,
    charWidth: 8, charHeight: 8, bytesPerGlyph: 8,
    bitOrder: 'msb-left', offset: 0,
    xBits: msb8,
    mapperId: 'petscii',
  },
  {
    id: 'c64-chargen-second',
    name: 'C64 (lowercase set)',
    url: '/fonts/c64/chargen.bin',
    computer: 'Commodore 64',
    description: 'C64 CHARGEN second 256 glyphs',
    glyphCount: 256,
    charWidth: 8, charHeight: 8, bytesPerGlyph: 8,
    bitOrder: 'msb-left', offset: 2048,
    xBits: msb8,
    mapperId: 'petscii',
  },
  {
    id: 'vic20-chargen',
    name: 'Commodore VIC-20',
    url: '/fonts/vic20/vic20.bin',
    computer: 'Commodore VIC-20',
    description: 'VIC-20 CHARGEN (2 sets, 4096B)',
    glyphCount: 512,
    charWidth: 8, charHeight: 8, bytesPerGlyph: 8,
    bitOrder: 'msb-left', offset: 0,
    xBits: msb8,
    mapperId: 'petscii',
  },
  {
    id: 'pet-2001',
    name: 'PET 2001',
    url: '/fonts/pet/pet-2001.bin',
    computer: 'Commodore PET',
    description: 'PET 2001 character ROM (2048B)',
    glyphCount: 256,
    charWidth: 8, charHeight: 8, bytesPerGlyph: 8,
    bitOrder: 'msb-left', offset: 0,
    xBits: msb8,
    mapperId: 'petscii',
  },
  {
    id: 'pet-4032',
    name: 'PET 4032',
    url: '/fonts/pet/pet-4032.bin',
    computer: 'Commodore PET',
    description: 'PET 4032 character ROM (4096B)',
    glyphCount: 512,
    charWidth: 8, charHeight: 8, bytesPerGlyph: 8,
    bitOrder: 'msb-left', offset: 0,
    xBits: msb8,
    mapperId: 'petscii',
  },
  {
    id: 'apple1',
    name: 'Apple 1',
    url: '/fonts/apple1.vid',
    computer: 'Apple 1',
    description: 'Apple 1 character generator (128 glyphs, 1024B)',
    glyphCount: 128,
    charWidth: 8, charHeight: 8, bytesPerGlyph: 8,
    bitOrder: 'lsb-left', offset: 0,
    xBits: lsb8,
    mapperId: 'ascii',
  },
  {
    id: 'cga-thick',
    name: 'IBM CGA (thick)',
    url: '/fonts/cga/cga-thick.bin',
    computer: 'IBM CGA',
    description: 'CGA 8×8 thick font (2048B)',
    glyphCount: 256,
    charWidth: 8, charHeight: 8, bytesPerGlyph: 8,
    bitOrder: 'msb-left', offset: 0,
    xBits: msb8,
    mapperId: 'ascii',
  },
  {
    id: 'cga-thin',
    name: 'IBM CGA (thin)',
    url: '/fonts/cga/cga-thin.bin',
    computer: 'IBM CGA',
    description: 'CGA 8×8 thin font (2048B)',
    glyphCount: 256,
    charWidth: 8, charHeight: 8, bytesPerGlyph: 8,
    bitOrder: 'msb-left', offset: 0,
    xBits: msb8,
    mapperId: 'ascii',
  },
  {
    id: 'mda-cga',
    name: 'MDA (CGA thick, 8×14 cell)',
    url: '/fonts/cga/cga-thick.bin',
    computer: 'IBM MDA',
    description: 'MDA using CGA thick glyphs in 8×14 cell',
    glyphCount: 256,
    charWidth: 8, charHeight: 8, bytesPerGlyph: 8,
    cellWidth: 8, cellHeight: 14,
    bitOrder: 'msb-left', offset: 0,
    xBits: msb8,
    mapperId: 'ascii',
  },
  {
    id: 'trs80-m1',
    name: 'TRS-80 Model I',
    url: '/fonts/trs80/m1-chargen.bin',
    computer: 'TRS-80 Model I',
    description: 'TRS-80 Model I char gen (128 glyphs, 1024B)',
    glyphCount: 128,
    charWidth: 6, charHeight: 8, bytesPerGlyph: 8,
    bitOrder: 'msb-left', offset: 0,
    xBits: [0, 1, 2, 3, 4, 5],
    mapperId: 'ascii',
  },
  {
    id: 'trs80-m3',
    name: 'TRS-80 Model III',
    url: '/fonts/trs80/m3-chargen.bin',
    computer: 'TRS-80 Model III',
    description: 'TRS-80 Model III char gen (256 glyphs, 2048B)',
    glyphCount: 256,
    charWidth: 8, charHeight: 8, bytesPerGlyph: 8,
    cellWidth: 8, cellHeight: 12,
    bitOrder: 'msb-left', offset: 0,
    xBits: lsb8,
    mapperId: 'ascii',
  },
  {
    id: 'trs80-m3-double',
    name: 'TRS-80 Model III (double width)',
    url: '/fonts/trs80/m3-chargen.bin',
    computer: 'TRS-80 Model III',
    description: 'TRS-80 Model III double-width (same font, 16px cell)',
    glyphCount: 256,
    charWidth: 8, charHeight: 8, bytesPerGlyph: 8,
    cellWidth: 16, cellHeight: 12,
    scaleX: 2,
    bitOrder: 'msb-left', offset: 0,
    xBits: lsb8,
    mapperId: 'ascii',
  },
  {
    id: 'cpc-464',
    name: 'Amstrad CPC 464',
    url: '/fonts/cpc/cpc464-chargen.bin',
    computer: 'Amstrad CPC',
    description: 'CPC 464 character generator (2048B, offset 0x3800)',
    glyphCount: 256,
    charWidth: 8, charHeight: 8, bytesPerGlyph: 8,
    cellWidth: 8, cellHeight: 8,
    bitOrder: 'msb-left', offset: 0,
    xBits: msb8,
    mapperId: 'ascii',
  },
  {
    id: 'cpc-6128',
    name: 'Amstrad CPC 6128',
    url: '/fonts/cpc/cpc6128-chargen.bin',
    computer: 'Amstrad CPC',
    description: 'CPC 6128 character generator (2048B, same as 464)',
    glyphCount: 256,
    charWidth: 8, charHeight: 8, bytesPerGlyph: 8,
    cellWidth: 8, cellHeight: 8,
    bitOrder: 'msb-left', offset: 0,
    xBits: msb8,
    mapperId: 'ascii',
  },
  {
    id: 'cpc-664',
    name: 'Amstrad CPC 664',
    url: '/fonts/cpc/cpc664-chargen.bin',
    computer: 'Amstrad CPC',
    description: 'CPC 664 character generator (2048B, same as 464)',
    glyphCount: 256,
    charWidth: 8, charHeight: 8, bytesPerGlyph: 8,
    cellWidth: 8, cellHeight: 8,
    bitOrder: 'msb-left', offset: 0,
    xBits: msb8,
    mapperId: 'ascii',
  },
  {
    id: 'kaypro-2',
    name: 'Kaypro II',
    url: '/fonts/kaypro/kaypro2.u43',
    computer: 'Kaypro II',
    description: 'Kaypro II 81-146A character ROM upper half (2048B)',
    glyphCount: 128,
    charWidth: 7, charHeight: 8, bytesPerGlyph: 8,
    cellWidth: 7, cellHeight: 8,
    bitOrder: 'msb-left', offset: 1024,
    xBits: [-1, 4, 3, 2, 1, 0, -1],
    invertBits: true,
    mapperId: 'ascii',
  },
  {
    id: 'kaypro-4',
    name: 'Kaypro 4/84',
    url: '/fonts/kaypro/kaypro4.u9',
    computer: 'Kaypro 4/84',
    description: 'Kaypro 4/84 font (4096B, 8x16)',
    glyphCount: 256,
    charWidth: 8, charHeight: 16, bytesPerGlyph: 16,
    cellWidth: 8, cellHeight: 16,
    bitOrder: 'msb-left', offset: 0,
    xBits: msb8,
    mapperId: 'ascii',
  },
  {
    id: 'osborne',
    name: 'Osborne 1',
    url: '/fonts/kaypro/kaypro4.u9',
    computer: 'Osborne',
    description: 'Osborne 1 font (CP/M 8x8, Kaypro fallback)',
    glyphCount: 128,
    charWidth: 8, charHeight: 8, bytesPerGlyph: 8,
    cellWidth: 8, cellHeight: 8,
    bitOrder: 'msb-left', offset: 0,
    xBits: msb8,
    mapperId: 'ascii',
    sourcePath: 'bitsavers: E98_020E3.BIN (pierwsze 8 z 16B/glyph, pierwsze 128 glyphów)',
  },
  {
    id: 'rainbow-100-narrow',
    name: 'DEC Rainbow 100 (132 col)',
    url: '/fonts/rainbow/rainbow-chargen-8x8.bin',
    computer: 'DEC',
    description: 'DEC Rainbow 100 narrow chargen (6px cell, 132-col)',
    glyphCount: 128,
    charWidth: 8, charHeight: 8, bytesPerGlyph: 8,
    cellWidth: 6, cellHeight: 8,
    bitOrder: 'msb-left', offset: 0,
    xBits: [7, 6, 5, 4, 3, 2],
    mapperId: 'ascii',
    sourcePath: 'bitsavers: E98_020E3.BIN (132-col narrow mode)',
  },
  {
    id: 'sinclair-ql',
    name: 'Sinclair QL',
    url: '/fonts/kaypro/kaypro4.u9',
    computer: 'Sinclair',
    description: 'Sinclair QL font (8x8 cell, Kaypro fallback)',
    glyphCount: 256,
    charWidth: 8, charHeight: 16, bytesPerGlyph: 16,
    cellWidth: 8, cellHeight: 8,
    bitOrder: 'msb-left', offset: 0,
    xBits: msb8,
    mapperId: 'ascii',
    sourcePath: 'QL ROM (zastępczy: Kaypro 4/84, 8x8)',
  },
  {
    id: 'otrona',
    name: 'Otrona Attache',
    url: '/fonts/otrona/otrona-g-chargen.bin',
    computer: 'Otrona',
    description: 'Otrona Attache character generator (4096B, 8x16, cell 8x10)',
    glyphCount: 256,
    charWidth: 8, charHeight: 16, bytesPerGlyph: 16,
    cellWidth: 8, cellHeight: 10,
    bitOrder: 'msb-left', offset: 0,
    xBits: msb8,
    mapperId: 'ascii',
    sourcePath: 'retroarchive: otrona-g.rom (offset 0, 16B/glyph)',
  },
  {
    id: 'xerox-820',
    name: 'Xerox 820-II',
    url: '/fonts/xerox/x2401u57-chargen.bin',
    computer: 'Xerox',
    description: 'Xerox 820-II character generator (2048B, 8x8, LSB-first)',
    glyphCount: 256,
    charWidth: 8, charHeight: 8, bytesPerGlyph: 8,
    cellWidth: 8, cellHeight: 8,
    bitOrder: 'msb-left', offset: 0,
    xBits: msb8,
    mapperId: 'ascii',
    sourcePath: 'retroarchive: x2401u57.rom (offset 0, MSB-first)',
  },
  {
    id: 'morrow-md3',
    name: 'Morrow MD3',
    url: '/fonts/kaypro/kaypro4.u9',
    computer: 'Morrow',
    description: 'Morrow MD3 font (CP/M 8x12, approximacja przez Kaypro 4/84)',
    glyphCount: 256,
    charWidth: 8, charHeight: 16, bytesPerGlyph: 16,
    cellWidth: 8, cellHeight: 12,
    bitOrder: 'msb-left', offset: 0,
    xBits: msb8,
    mapperId: 'ascii',
    sourcePath: 'retroarchive: md3-31.rom (brak czystego chargenu)',
  },
  {
    id: 'rainbow-100',
    name: 'DEC Rainbow 100',
    url: '/fonts/rainbow/rainbow-chargen-8x8.bin',
    computer: 'DEC',
    description: 'DEC Rainbow 100 chargen (E98_020E3, 8x8, 2048B)',
    glyphCount: 256,
    charWidth: 8, charHeight: 8, bytesPerGlyph: 8,
    cellWidth: 8, cellHeight: 8,
    bitOrder: 'msb-left', offset: 0,
    xBits: msb8,
    mapperId: 'ascii',
    sourcePath: 'rbw-char.rom (offset 0, needs 8x8 extraction)',
  },
  {
    id: 'epson-px8',
    name: 'Epson PX-8',
    url: '/fonts/kaypro/kaypro4.u9',
    computer: 'Epson',
    description: 'Epson PX-8 font (CP/M 8x8, approximacja przez Kaypro 4/84)',
    glyphCount: 256,
    charWidth: 8, charHeight: 16, bytesPerGlyph: 16,
    cellWidth: 8, cellHeight: 8,
    bitOrder: 'msb-left', offset: 0,
    xBits: msb8,
    mapperId: 'ascii',
    sourcePath: 'retroarchive: PX-8 ROM (brak czystego chargenu)',
  },
  {
    id: 'otrona',
    name: 'Otrona Attache',
    url: '/fonts/kaypro/kaypro4.u9',
    computer: 'Otrona Attache',
    description: 'Otrona Attache (Kaypro font, 8×8 cell)',
    glyphCount: 256,
    charWidth: 8, charHeight: 16, bytesPerGlyph: 16,
    cellWidth: 8, cellHeight: 8,
    bitOrder: 'msb-left', offset: 0,
    xBits: msb8,
    mapperId: 'ascii',
  },
  {
    id: 'morrow-md3',
    name: 'Morrow MD3',
    url: '/fonts/kaypro/kaypro4.u9',
    computer: 'Morrow MD3',
    description: 'Morrow MD3 (Kaypro font, 8×12 cell)',
    glyphCount: 256,
    charWidth: 8, charHeight: 16, bytesPerGlyph: 16,
    cellWidth: 8, cellHeight: 12,
    bitOrder: 'msb-left', offset: 0,
    xBits: msb8,
    mapperId: 'ascii',
  },
  {
    id: 'rainbow-100',
    name: 'DEC Rainbow 100',
    url: '/fonts/kaypro/kaypro4.u9',
    computer: 'DEC Rainbow 100',
    description: 'DEC Rainbow 100 (Kaypro font, 8×10 cell)',
    glyphCount: 256,
    charWidth: 8, charHeight: 16, bytesPerGlyph: 16,
    cellWidth: 8, cellHeight: 10,
    bitOrder: 'msb-left', offset: 0,
    xBits: msb8,
    mapperId: 'ascii',
  },
  {
    id: 'epson-px8',
    name: 'Epson PX-8 Geneva',
    url: '/fonts/kaypro/kaypro4.u9',
    computer: 'Epson PX-8',
    description: 'Epson PX-8 (Kaypro font, 8×8 cell)',
    glyphCount: 256,
    charWidth: 8, charHeight: 16, bytesPerGlyph: 16,
    cellWidth: 8, cellHeight: 8,
    bitOrder: 'msb-left', offset: 0,
    xBits: msb8,
    mapperId: 'ascii',
  },
];

export function getFontPreset(id: string): FontPreset | undefined {
  return fontPresets.find(p => p.id === id);
}

export function getMapperIdForFont(fontId: string): 'ascii' | 'petscii' {
  return fontPresets.find(p => p.id === fontId)?.mapperId ?? 'ascii';
}
