import type { LoadBitmapFontOptions } from './FontLoader';

export interface FontPreset extends LoadBitmapFontOptions {
  glyphCount: number;
  charWidth: number;
  charHeight: number;
  bytesPerGlyph: number;
  computer: string;
  description: string;
  mapperId: 'ascii' | 'petscii';
}

const msb8 = [7, 6, 5, 4, 3, 2, 1, 0];
const lsb8 = [0, 1, 2, 3, 4, 5, 6, 7];

export const fontPresets: FontPreset[] = [
  {
    id: 'zx-spectrum',
    name: 'ZX Spectrum',
    url: '/fonts/zx-spectrum/zx-spectrum.bin',
    computer: 'ZX Spectrum',
    description: 'ZX Spectrum ROM font (1024B, 128 glyphs)',
    glyphCount: 128,
    charWidth: 8, charHeight: 8, bytesPerGlyph: 8,
    bitOrder: 'msb-left', offset: 0,
    xBits: msb8,
    mapperId: 'ascii',
  },
  {
    id: 'c64-chargen',
    name: 'Commodore 64',
    url: '/fonts/c64/chargen.bin',
    computer: 'Commodore 64',
    description: 'C64 CHARGEN (2 sets, 4096B)',
    glyphCount: 512,
    charWidth: 8, charHeight: 8, bytesPerGlyph: 8,
    bitOrder: 'msb-left', offset: 0,
    xBits: msb8,
    mapperId: 'petscii',
  },
  {
    id: 'c64-chargen-first',
    name: 'C64 (uppercase set)',
    url: '/fonts/c64/chargen.bin',
    computer: 'Commodore 64',
    description: 'C64 CHARGEN first 256 glyphs',
    glyphCount: 256,
    charWidth: 8, charHeight: 8, bytesPerGlyph: 8,
    bitOrder: 'msb-left', offset: 0,
    xBits: msb8,
    mapperId: 'petscii',
  },
  {
    id: 'c64-chargen-second',
    name: 'C64 (lowercase set)',
    url: '/fonts/c64/chargen.bin',
    computer: 'Commodore 64',
    description: 'C64 CHARGEN second 256 glyphs',
    glyphCount: 256,
    charWidth: 8, charHeight: 8, bytesPerGlyph: 8,
    bitOrder: 'msb-left', offset: 2048,
    xBits: msb8,
    mapperId: 'petscii',
  },
  {
    id: 'vic20-chargen',
    name: 'Commodore VIC-20',
    url: '/fonts/vic20/vic20.bin',
    computer: 'Commodore VIC-20',
    description: 'VIC-20 CHARGEN (2 sets, 4096B)',
    glyphCount: 512,
    charWidth: 8, charHeight: 8, bytesPerGlyph: 8,
    bitOrder: 'msb-left', offset: 0,
    xBits: msb8,
    mapperId: 'petscii',
  },
  {
    id: 'pet-2001',
    name: 'PET 2001',
    url: '/fonts/pet/pet-2001.bin',
    computer: 'Commodore PET',
    description: 'PET 2001 character ROM (2048B)',
    glyphCount: 256,
    charWidth: 8, charHeight: 8, bytesPerGlyph: 8,
    bitOrder: 'msb-left', offset: 0,
    xBits: msb8,
    mapperId: 'petscii',
  },
  {
    id: 'pet-4032',
    name: 'PET 4032',
    url: '/fonts/pet/pet-4032.bin',
    computer: 'Commodore PET',
    description: 'PET 4032 character ROM (4096B)',
    glyphCount: 512,
    charWidth: 8, charHeight: 8, bytesPerGlyph: 8,
    bitOrder: 'msb-left', offset: 0,
    xBits: msb8,
    mapperId: 'petscii',
  },
  {
    id: 'apple1',
    name: 'Apple 1',
    url: '/fonts/apple1.vid',
    computer: 'Apple 1',
    description: 'Apple 1 character generator (128 glyphs, 1024B)',
    glyphCount: 128,
    charWidth: 8, charHeight: 8, bytesPerGlyph: 8,
    bitOrder: 'lsb-left', offset: 0,
    xBits: lsb8,
    mapperId: 'ascii',
  },
  {
    id: 'cga-thick',
    name: 'IBM CGA (thick)',
    url: '/fonts/cga/cga-thick.bin',
    computer: 'IBM CGA',
    description: 'CGA 8×8 thick font (2048B)',
    glyphCount: 256,
    charWidth: 8, charHeight: 8, bytesPerGlyph: 8,
    bitOrder: 'msb-left', offset: 0,
    xBits: msb8,
    mapperId: 'ascii',
  },
  {
    id: 'cga-thin',
    name: 'IBM CGA (thin)',
    url: '/fonts/cga/cga-thin.bin',
    computer: 'IBM CGA',
    description: 'CGA 8×8 thin font (2048B)',
    glyphCount: 256,
    charWidth: 8, charHeight: 8, bytesPerGlyph: 8,
    bitOrder: 'msb-left', offset: 0,
    xBits: msb8,
    mapperId: 'ascii',
  },
  {
    id: 'mda-8x14',
    name: 'IBM MDA 8×14',
    url: '/fonts/mda/mda-8x14.bin',
    computer: 'IBM MDA',
    description: 'MDA 8×14 font (3584B)',
    glyphCount: 256,
    charWidth: 8, charHeight: 14, bytesPerGlyph: 14,
    bitOrder: 'msb-left', offset: 0,
    xBits: msb8,
    mapperId: 'ascii',
  },
  {
    id: 'trs80-m1',
    name: 'TRS-80 Model I',
    url: '/fonts/trs80/m1-chargen.bin',
    computer: 'TRS-80 Model I',
    description: 'TRS-80 Model I char gen (128 glyphs, 1024B)',
    glyphCount: 128,
    charWidth: 6, charHeight: 8, bytesPerGlyph: 8,
    bitOrder: 'msb-left', offset: 0,
    xBits: [0, 1, 2, 3, 4, 5],
    mapperId: 'ascii',
  },
  {
    id: 'trs80-m3',
    name: 'TRS-80 Model III',
    url: '/fonts/trs80/m3-chargen.bin',
    computer: 'TRS-80 Model III',
    description: 'TRS-80 Model III char gen (256 glyphs, 2048B)',
    glyphCount: 256,
    charWidth: 8, charHeight: 8, bytesPerGlyph: 8,
    bitOrder: 'msb-left', offset: 0,
    xBits: lsb8,
    mapperId: 'ascii',
  },
  {
    id: 'kaypro-2',
    name: 'Kaypro II',
    url: '/fonts/kaypro/kaypro2.u43',
    computer: 'Kaypro II',
    description: 'Kaypro II font (2048B)',
    glyphCount: 256,
    charWidth: 7, charHeight: 8, bytesPerGlyph: 8,
    bitOrder: 'msb-left', offset: 0,
    xBits: [-1, 4, 3, 2, 1, 0, -1],
    invertBits: true,
    mapperId: 'ascii',
  },
  {
    id: 'kaypro-4',
    name: 'Kaypro 4/84',
    url: '/fonts/kaypro/kaypro4.u9',
    computer: 'Kaypro 4/84',
    description: 'Kaypro 4/84 font (4096B)',
    glyphCount: 256,
    charWidth: 8, charHeight: 16, bytesPerGlyph: 16,
    bitOrder: 'msb-left', offset: 0,
    xBits: msb8,
    mapperId: 'ascii',
  },
];

export function getFontPreset(id: string): FontPreset | undefined {
  return fontPresets.find(p => p.id === id);
}

export function getMapperIdForFont(fontId: string): 'ascii' | 'petscii' {
  return fontPresets.find(p => p.id === fontId)?.mapperId ?? 'ascii';
}
